CREATE DATABASE prova_exer02;
use prova_exer02;

CREATE TABLE PRODUTOS(
	ID INT NOT NULL auto_increment,
    PRIMARY KEY (id),
    NOME VARCHAR(30),
    CODIDO_BARRA VARCHAR(30),
    PRECO DECIMAL(5,2),
    QUANTIDADE INT
);

CREATE TABLE ESTOQUE(
	ID INT NOT NULL auto_increment,
    PRIMARY KEY (id),
    NOME VARCHAR(30),
    NUMERO INT,
    QUANTIDADE INT,
    ID_PRODUTOS INT NOT NULL,
    foreign key(ID_PRODUTOS) REFERENCES PRODUTOS(ID)
);

CREATE TABLE FUNCIONARIO(
	ID INT NOT NULL auto_increment,
    PRIMARY KEY (id),
    NOME VARCHAR(30),
    IDADE INT
);

CREATE TABLE VENDA(
	ID INT NOT NULL auto_increment,
    PRIMARY KEY (id),
    PRECO_FINAL DECIMAL(5,2),
    ID_FUNCIONARIOS INT NOT NULL,
    foreign key(ID_FUNCIONARIOS) REFERENCES FUNCIONARIO(ID)
);

CREATE TABLE ESTOQUE_VENDA(
	ID INT NOT NULL auto_increment,
    PRIMARY KEY (id),
    QUANTIDADE_PRODUTO DECIMAL(5,2),
    ID_ESTOQUE INT NOT NULL,
    ID_VENDA INT NOT NULL,
    foreign key(ID_ESTOQUE) REFERENCES ESTOQUE(ID),
    foreign key(ID_VENDA) REFERENCES VENDA(ID)
);



INSERT INTO PRODUTOS VALUES (1, "SADIA", "00012301230-1230120", 52, 75);
INSERT INTO PRODUTOS VALUES (2, "BOLACHA", "00012301230-1230120", 12.34, 75);

INSERT INTO ESTOQUE VALUES (1, "Zequinho depositos" , 95, 5, 1);

INSERT INTO FUNCIONARIO VALUES (1, "Fernando", 25);

INSERT INTO VENDA VALUES (1, 100.00, 1);

INSERT INTO ESTOQUE_VENDA VALUES (1,25,1,1);

SELECT * FROM PRODUTOS;
SELECT * FROM ESTOQUE;
SELECT * FROM FUNCIONARIO;
SELECT * FROM VENDA;
SELECT * FROM PRODUTO_VENDA;

select PV.QUANTIDADE FROM PRODUTO_VENDA PV;
